---
name: 'Install released package from PyPI'

# Run weekly, and also run on demand
'on':
  schedule:
    - cron: '0 12 * * 3'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: 'pip install pipdeptree markdown-xblock'
      - name: Run pipdeptree
        run: pipdeptree
